### ISSUE TITLE
Extract Presentation.Web.Tests IResultMatcherExtensions

### ISSUE THREAD

**Issue by wintondeshong** [AndcultureCode/AndcultureCode.DotnetReact.Boilerplate#22]
There are some helpful IResult related testing matcher extensions that can be moved to the AndcultureCode.CSharp.Testing package.

**Comment by brandongregoryscott** [comment]
@wintondeshong I'll take this one! Been meaning to do this for a while.

**Comment by brandongregoryscott** [comment]
Two thoughts/questions as I dig into this more:

1. `Controller.ERROR_RESOURCE_NOT_FOUND_KEY` is currently in the `Presentation.Web` project, but hasn't been extracted anywhere else yet. Should we move this to an `ErrorConstants` class in `AndcultureCode.CSharp.Core` so that the web package and test package can utilize it? 

If so, I will port the `ShouldHaveBasicError` method and follow it up with another PR to port the `ShouldHaveResourceNotFoundError` method.

2. Do we want to start unit testing these testing extensions? Ideally, there shouldn't be too much logic in these methods, or too much changing for that matter, but I don't see the harm in adding some basic coverage. Only asking because I'm adding some additional logic in some of the methods that were missing (as per the comments in the extension methods in this project), and I only see a unit test suite for `FactorySettings`

If we're okay with that, I'll probably backfill some tests for the other methods in that extensions class as well.

**Comment by wintondeshong** [comment]
@brandongregoryscott thanks for taking on this issue. Below are some thoughts...

1. Sure, being this is such a generic error code it could definitely be promoted to Core.
2. I'd say yes to unit testing them. Should be fairly easy to write and being these are now a library, we really should.

**Comment by brandongregoryscott** [comment]
Opening this back up until the original code is pulled out in favor of the updated package(s)
